# A sample worklow to demonstrate Kyma OIDC connect feature
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        name: set token in output
        id: token
        env:
          CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
        with:
          script: |
            const owner = process.env.GITHUB_REPOSITORY_OWNER;
            const token = await core.getIDToken({subject: owner, audience: process.env.CLUSTER_ID});
            core.setOutput('id_token', token);
      - name: Access Kyma runtime
        env:
          OIDC_TOKEN: ${{ steps.token.outputs.id_token }}
          KUBECONFIG: $HOME/.kube/config
          CLUSTER_ID: ${{ secrets.CLUSTER_ID }}
          K8S_API_SERVER: ${{ secrets.K8S_API_SERVER }}
          CA_CERT_STRING: ${{ secrets.CA_CERT_STRING }}
          REQUEST_LOGGER: ${{ secrets.REQUEST_LOGGER }}
        run: |
          # make a curl call
          curl -X GET -H "Authorization: Bearer $OIDC_TOKEN" https://$REQUEST_LOGGER -v
          # Write CA certificate to file
          echo $CA_CERT_STRING | base64 -d > /tmp/ca.crt
          # Set up kubeconfig (replace with your actual cluster details)
          kubectl config set-cluster $CLUSTER_ID \
            --server=https://$K8S_API_SERVER \
            --certificate-authority=/tmp/ca.crt
          kubectl config set-credentials github-oidc-user \
            --token="$OIDC_TOKEN"
          kubectl config set-context $CLUSTER_ID \
            --cluster=$CLUSTER_ID \
            --user=github-oidc-user
          kubectl config use-context $CLUSTER_ID
          
          # Test authentication
          kubectl config view
          kubectl get pods
